<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="ProcesoCitas.aspx.cs" Inherits="VeterinariaWeb.Procesos.ProcesoCitas" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ScriptContent" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <h2>Manejo de Citas</h2>
    <div class="form-horizontal">
        <%-- Este h4 para informar cual acción esta realizando --%>
        <h4>Generar Citas</h4>   

        <div class="form-group">
            <asp:Label ID="Label1" runat="server" Text="Fecha Cita" CssClass="control-label col-md-2"></asp:Label>
            <div class="col-md-10">
                <asp:TextBox ID="txtFechaCita" runat="server" CssClass="form-control entrada" placeholder="Fecha Cita"></asp:TextBox>
                <ajaxToolkit:CalendarExtender runat="server" Format="dd/MM/yyyy" PopupButtonID="ImageButton" BehaviorID="txtFecha_CalendarExt"
                    TargetControlID="txtFechaCita" ID="txtFecha_CalendarExt"> </ajaxToolkit:CalendarExtender>
                <asp:Image ID="ImageButton" ImageUrl="~/img/calendar.png" runat="server" AlternateText="Fecha" ImageAlign="Left"/>
                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Ingrese la fecha de la cita" ControlToValidate="txtFechaCita" Display="Dynamic" ForeColor="#cc0000"></asp:RequiredFieldValidator>
            </div>
        </div>

        <div class="form-group">

            <asp:Label ID="Label2" runat="server" Text="Paciente ID" CssClass="control-label col-md-2"></asp:Label>
            <div class="col-md-10">
                <%-- Copie todas las clases de css para cada etiqueta , por ejemplo si quita la etiqueta "entrada" el textbox queda del ancho de la pantalla --%>
                 <asp:TextBox ID="txtPacienteID" runat="server" CssClass="form-control entrada"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Ingrese el Paciente" ControlToValidate="txtPacienteID" Display="Dynamic" ForeColor="#cc0000"></asp:RequiredFieldValidator>
            </div>
        </div>

          <div class="form-group">
            <asp:Label ID="Label3" runat="server" Text="Descripción" CssClass="control-label col-md-2"></asp:Label>
            <div class="col-md-10">
                <asp:TextBox ID="txtDescripcion" runat="server" CssClass="form-control entrada"></asp:TextBox>
                 <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Ingrese una descripción" ControlToValidate="txtDescripcion" Display="Dynamic" ForeColor="#cc0000"></asp:RequiredFieldValidator>
            </div>
        </div>



      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                
                <asp:Button ID="btnNuevo" runat="server" Text="Nuevo" CssClass="btn btn-default" OnClick="btnNuevo_Click"/>
            </div>
        </div>

         

      </div>

    <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              
            <td colspan="2">
                <asp:UpdatePanel runat="server">
                    <ContentTemplate>
                <h4>Citas Programadas</h4>
             <tr>
                <td colspan="2">
                        <asp:GridView ID="grvCitas" runat="server"
                    DataKeyNames="CitaID"  
                    AutoGenerateColumns="false"
                    AutoGenerateEditButton ="true"
                    AutoGenerateDeleteButton ="true"
                    OnRowCancelingEdit="grvCitas_RowCancelingEdit"
                    OnRowEditing="grvCitas_RowEditing"
                    OnRowDataBound="grvCitas_RowDataBound"
                    OnRowUpdating="grvCitas_RowUpdating"
                    OnRowDeleting="grvCitas_RowDeleting">

                    <Columns>
                       
                        
                        
                        <asp:TemplateField HeaderText="Fecha">
                            <ItemTemplate>
                                <asp:Label ID="lblFecha" runat="server" Text='<%# Eval("fechaCita") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="fechaCita" runat="server" Text='<%# Bind("fechaCita") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Paciente">
                            <ItemTemplate>
                                <asp:Label ID="lblPaciente" runat="server" Text='<%# Eval("pacienteID") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="pacienteID" runat="server" Text='<%# Bind("pacienteID") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                         <asp:TemplateField HeaderText="Descripción">
                            <ItemTemplate>
                                <asp:Label ID="lblDescripcion" runat="server" Text='<%# Eval("descripcionCita") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="descripcionCita" runat="server" Text='<%# Bind("descripcionCita") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                         <asp:TemplateField HeaderText="Nombre Paciente">
                            <ItemTemplate>
                                <asp:Label ID="lblNombrePaciente" runat="server" Text='<%# Eval("nombrePaciente") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="nombrePaciente" runat="server" Text='<%# Bind("nombrePaciente") %>' ReadOnly="true"></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        
                       <%--  <asp:TemplateField HeaderText="Nombre Dueño">
                            <ItemTemplate>
                                <asp:Label ID="lblNombreDueño" runat="server" Text='<%# Eval("nombreDuenno") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="nombreDuenno" runat="server" Text='<%# Bind("nombreDuenno") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>--%>
                        

                       </Columns>
                </asp:GridView>
                    </ContentTemplate>
                    <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="btnNuevo" EventName="Click" />
                    </Triggers>
                </asp:UpdatePanel>
                </td>
            
            </div>
        </div>


</asp:Content>
