<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="NuevoEnfermedad.aspx.cs" Inherits="VeterinariaWeb.Mantenimientos.NuevoEnfermedad" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>


<asp:Content ID="Content2" ContentPlaceHolderID="ScriptContent" runat="server">
</asp:Content>


<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <h2>Manejo de enfermedades</h2>
    <div class="form-horizontal">
        <%-- Este h4 para informar cual acción esta realizando --%>
        <h4>Nueva Enfermedad</h4>
        <%-- Aquí comienza el maquetado para un control ejemplo un textbox --%>
        


        <div class="form-group">

            <asp:Label ID="Label1" runat="server" Text="Nombre Enfermedad" CssClass="control-label col-md-2"></asp:Label>
            <div class="col-md-10">
                <%-- Copie todas las clases de css para cada etiqueta , por ejemplo si quita la etiqueta "entrada" el textbox queda del ancho de la pantalla --%>
                 <asp:TextBox ID="txtNombreEnfermedad" runat="server" CssClass="form-control entrada"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Ingrese el nombre de la enfermedad" ControlToValidate="txtNombreEnfermedad" Display="Dynamic" ForeColor="#cc0000"></asp:RequiredFieldValidator>
            </div>
        </div>


         <div class="form-group">
            <asp:Label ID="Label3" runat="server" Text="Paciente ID" CssClass="control-label col-md-2"></asp:Label>
            <div class="col-md-10"> 
                <asp:TextBox ID="txtPacienteID" runat="server" CssClass="form-control entrada"></asp:TextBox>
                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Ingrese el paciente" ControlToValidate="txtPacienteID" Display="Dynamic" ForeColor="#cc0000"></asp:RequiredFieldValidator>
            </div>
        </div>


         <div class="form-group">
            <asp:Label ID="Label4" runat="server" Text="Sintómas" CssClass="control-label col-md-2"></asp:Label>
            <div class="col-md-10">
                <asp:TextBox ID="txtSintomas" runat="server" CssClass="form-control entrada"></asp:TextBox>
                 <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="Ingrese los sintomas" ControlToValidate="txtSintomas" Display="Dynamic" ForeColor="#cc0000"></asp:RequiredFieldValidator>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <%--<asp:Button ID="btnNuevo" runat="server" Text="Nuevo" CssClass="btn btn-default" OnClick="btnNuevo_Click" OnClientClick="return ConfirmarIngreso();"/>--%>
                <asp:Button ID="btnNuevo" runat="server" Text="Nuevo" CssClass="btn btn-default" OnClick="btnNuevo_Click"/>
            </div>
        </div>

         

      </div>

    <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              
            <td colspan="2">
                <asp:UpdatePanel runat="server">
                    <ContentTemplate>
                <h4>Enfermedades registradas</h4>
             <tr>
                <td colspan="2">
                        <asp:GridView ID="grvEnfermedades" runat="server"
                    DataKeyNames="EnfermedadID" 
                    AutoGenerateColumns="false"
                    AutoGenerateEditButton ="true"
                    AutoGenerateDeleteButton ="true"
                    OnRowCancelingEdit="grvEnfermedades_RowCancelingEdit"
                    OnRowEditing="grvEnfermedades_RowEditing"
                    OnRowDataBound="grvEnfermedades_RowDataBound"
                    OnRowUpdating="grvEnfermedades_RowUpdating"
                    OnRowDeleting="grvEnfermedades_RowDeleting">

                    <Columns>
                       
                        <asp:TemplateField HeaderText="Nombre Enfermedad">
                            <ItemTemplate>
                                <asp:Label ID="lblNombreEnfermedad" runat="server" Text='<%# Eval("nombreEnfermedad") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="nombreEnfermedad" runat="server" Text='<%# Bind("nombreEnfermedad") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        
                        
                        <asp:TemplateField HeaderText="Paciente ID">
                            <ItemTemplate>
                                <asp:Label ID="lblPaciente" runat="server" Text='<%# Eval("pacienteID") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="pacienteID" runat="server" Text='<%# Bind("pacienteID") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Nombre Paciente">
                            <ItemTemplate>
                                <asp:Label ID="lblPaciente" runat="server" Text='<%# Eval("nombrePaciente") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="nombrePaciente" runat="server" Text='<%# Bind("nombrePaciente") %>' ReadOnly="true"></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Sintómas">
                            <ItemTemplate>
                                <asp:Label ID="lblSintomas" runat="server" Text='<%# Eval("sintomasEnfermedad") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="sintomasEnfermedad" runat="server" Text='<%# Bind("sintomasEnfermedad") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                       </Columns>
                </asp:GridView>
                    </ContentTemplate>
                    <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="btnNuevo" EventName="Click" />
                    </Triggers>
                </asp:UpdatePanel>
                </td>
            
            </div>
        </div>



</asp:Content>
